
export const SOCIAL_PLATFORMS = [
  { value: 'Facebook', label: 'Facebook' },
  { value: 'YouTube', label: 'YouTube' },
  { value: 'Instagram', label: 'Instagram' },
  { value: 'Twitter', label: 'Twitter' },
  { value: 'LinkedIn', label: 'LinkedIn' },
  { value: 'Discord', label: 'Discord' },
  { value: 'WhatsApp', label: 'WhatsApp' },
  { value: 'TikTok', label: 'TikTok' },
  { value: 'WeChat', label: 'WeChat' },
  { value: 'Telegram', label: 'Telegram' },
  { value: 'Snapchat', label: 'Snapchat' },
  { value: 'Douyin', label: 'Douyin (Chinese TikTok)' },
  { value: 'Pinterest', label: 'Pinterest' },
  { value: 'Reddit', label: 'Reddit' },
  { value: 'Quora', label: 'Quora' },
  { value: 'Weibo', label: 'Sina Weibo' },
  { value: 'Threads', label: 'Threads' },
  { value: 'LINE', label: 'LINE' },
  { value: 'Tumblr', label: 'Tumblr' },
  { value: 'Twitch', label: 'Twitch' },
  { value: 'Viber', label: 'Viber' },
  { value: 'Clubhouse', label: 'Clubhouse' },
  { value: 'BeReal', label: 'BeReal' },
  { value: 'QQ', label: 'QQ' },
];
